<?xml version="1.0" encoding="UTF-8"?>
<Layout version="1.6.1">
  <Mode>Vertical</Mode>
  <X>1658</X>
  <Y>8</Y>
  <VerticalWidth>252</VerticalWidth>
  <VerticalHeight>375</VerticalHeight>
  <HorizontalWidth>-1</HorizontalWidth>
  <HorizontalHeight>-1</HorizontalHeight>
  <Settings>
    <TextColor>FFFFFFFF</TextColor>
    <BackgroundColor>FF160000</BackgroundColor>
    <BackgroundColor2>FF00020B</BackgroundColor2>
    <ThinSeparatorsColor>0400C2FF</ThinSeparatorsColor>
    <SeparatorsColor>1AC3C3C3</SeparatorsColor>
    <PersonalBestColor>FF16A6FF</PersonalBestColor>
    <AheadGainingTimeColor>FF00EDFF</AheadGainingTimeColor>
    <AheadLosingTimeColor>FF008C97</AheadLosingTimeColor>
    <BehindGainingTimeColor>FFCC7870</BehindGainingTimeColor>
    <BehindLosingTimeColor>FFCC3729</BehindLosingTimeColor>
    <BestSegmentColor>FFFFDA00</BestSegmentColor>
    <UseRainbowColor>True</UseRainbowColor>
    <NotRunningColor>FF7A7A7A</NotRunningColor>
    <PausedColor>FF7A7A7A</PausedColor>
    <TextOutlineColor>00000000</TextOutlineColor>
    <ShadowsColor>E4000000</ShadowsColor>
    <TimesFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAA9Pc3dhbGQgU2VtaUJvbGQAAEBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAAAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAMAAAAL]]></TimesFont>
    <TimerFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAA9Pc3dhbGQgU2VtaUJvbGQexzFCBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAAAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAIAAAAL]]></TimerFont>
    <TextFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAxPc3dhbGQgTGlnaHQAAGBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAAAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAMAAAAL]]></TextFont>
    <AlwaysOnTop>True</AlwaysOnTop>
    <ShowBestSegments>True</ShowBestSegments>
    <AntiAliasing>True</AntiAliasing>
    <DropShadows>True</DropShadows>
    <BackgroundType>VerticalGradient</BackgroundType>
    <BackgroundImage />
    <ImageOpacity>1</ImageOpacity>
    <ImageBlur>0</ImageBlur>
    <Opacity>1</Opacity>
  </Settings>
  <Components>
    <Component>
      <Path>LiveSplit.Subsplits.dll</Path>
      <Settings>
        <Version>1.7</Version>
        <CurrentSplitTopColor>FF3373F4</CurrentSplitTopColor>
        <CurrentSplitBottomColor>FF153574</CurrentSplitBottomColor>
        <VisualSplitCount>8</VisualSplitCount>
        <SplitPreviewCount>1</SplitPreviewCount>
        <MinimumMajorSplits>0</MinimumMajorSplits>
        <DisplayIcons>True</DisplayIcons>
        <ShowThinSeparators>False</ShowThinSeparators>
        <AlwaysShowLastSplit>True</AlwaysShowLastSplit>
        <SplitWidth>20</SplitWidth>
        <SplitTimesAccuracy>Seconds</SplitTimesAccuracy>
        <BeforeNamesColor>FFFFFFFF</BeforeNamesColor>
        <CurrentNamesColor>FFFFFFFF</CurrentNamesColor>
        <AfterNamesColor>FFFFFFFF</AfterNamesColor>
        <OverrideTextColor>False</OverrideTextColor>
        <BeforeTimesColor>FFFFFFFF</BeforeTimesColor>
        <CurrentTimesColor>FFFFFFFF</CurrentTimesColor>
        <AfterTimesColor>FFFFFFFF</AfterTimesColor>
        <OverrideTimesColor>False</OverrideTimesColor>
        <LockLastSplit>True</LockLastSplit>
        <IconSize>31</IconSize>
        <IconShadows>True</IconShadows>
        <SplitHeight>6</SplitHeight>
        <CurrentSplitGradient>Vertical</CurrentSplitGradient>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>01FFFFFF</BackgroundColor2>
        <BackgroundGradient>Alternating</BackgroundGradient>
        <SeparatorLastSplit>True</SeparatorLastSplit>
        <DeltasAccuracy>Tenths</DeltasAccuracy>
        <DropDecimals>True</DropDecimals>
        <OverrideDeltasColor>False</OverrideDeltasColor>
        <DeltasColor>FFFFFFFF</DeltasColor>
        <HeaderComparison>Current Comparison</HeaderComparison>
        <HeaderTimingMethod>Game Time</HeaderTimingMethod>
        <Display2Rows>False</Display2Rows>
        <IndentBlankIcons>True</IndentBlankIcons>
        <IndentSubsplits>True</IndentSubsplits>
        <HideSubsplits>False</HideSubsplits>
        <ShowSubsplits>True</ShowSubsplits>
        <CurrentSectionOnly>False</CurrentSectionOnly>
        <OverrideSubsplitColor>False</OverrideSubsplitColor>
        <SubsplitGradient>Plain</SubsplitGradient>
        <ShowHeader>True</ShowHeader>
        <IndentSectionSplit>True</IndentSectionSplit>
        <ShowIconSectionSplit>True</ShowIconSectionSplit>
        <ShowSectionIcon>True</ShowSectionIcon>
        <HeaderGradient>Vertical</HeaderGradient>
        <OverrideHeaderColor>False</OverrideHeaderColor>
        <HeaderText>True</HeaderText>
        <HeaderTimes>True</HeaderTimes>
        <HeaderAccuracy>Tenths</HeaderAccuracy>
        <SectionTimer>True</SectionTimer>
        <SectionTimerGradient>True</SectionTimerGradient>
        <SectionTimerAccuracy>Tenths</SectionTimerAccuracy>
        <SubsplitTopColor>8D000000</SubsplitTopColor>
        <SubsplitBottomColor>00FFFFFF</SubsplitBottomColor>
        <HeaderTopColor>2BFFFFFF</HeaderTopColor>
        <HeaderBottomColor>D8000000</HeaderBottomColor>
        <HeaderTextColor>FFFFFFFF</HeaderTextColor>
        <HeaderTimesColor>FFFFFFFF</HeaderTimesColor>
        <SectionTimerColor>FF777777</SectionTimerColor>
        <ShowColumnLabels>False</ShowColumnLabels>
        <LabelsColor>FFFFFFFF</LabelsColor>
        <Columns>
          <Settings>
            <Version>1.5</Version>
            <Name>+/-</Name>
            <Type>Delta</Type>
            <Comparison>Current Comparison</Comparison>
            <TimingMethod>Current Timing Method</TimingMethod>
          </Settings>
          <Settings>
            <Version>1.5</Version>
            <Name>Time</Name>
            <Type>SplitTime</Type>
            <Comparison>Current Comparison</Comparison>
            <TimingMethod>Current Timing Method</TimingMethod>
          </Settings>
        </Columns>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.DetailedTimer.dll</Path>
      <Settings>
        <Version>1.5</Version>
        <Height>75</Height>
        <Width>200</Width>
        <SegmentTimerSizeRatio>40</SegmentTimerSizeRatio>
        <TimerShowGradient>True</TimerShowGradient>
        <OverrideTimerColors>False</OverrideTimerColors>
        <SegmentTimerShowGradient>True</SegmentTimerShowGradient>
        <TimerFormat>1.23</TimerFormat>
        <SegmentTimerFormat>1.23</SegmentTimerFormat>
        <SegmentTimesAccuracy>Hundredths</SegmentTimesAccuracy>
        <TimerColor>FFAAAAAA</TimerColor>
        <SegmentTimerColor>FFAAAAAA</SegmentTimerColor>
        <SegmentLabelsColor>FFFFFFFF</SegmentLabelsColor>
        <SegmentTimesColor>FFFFFFFF</SegmentTimesColor>
        <SegmentLabelsFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAIEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></SegmentLabelsFont>
        <SegmentTimesFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAIEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAABAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></SegmentTimesFont>
        <SplitNameFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAMEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></SplitNameFont>
        <DisplayIcon>False</DisplayIcon>
        <IconSize>40</IconSize>
        <ShowSplitName>False</ShowSplitName>
        <SplitNameColor>FFFFFFFF</SplitNameColor>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Comparison>Current Comparison</Comparison>
        <Comparison2>Best Segments</Comparison2>
        <HideComparison>False</HideComparison>
        <TimingMethod>Game Time</TimingMethod>
        <DecimalsSize>35</DecimalsSize>
        <SegmentTimerDecimalsSize>35</SegmentTimerDecimalsSize>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.Timer.dll</Path>
      <Settings>
        <Version>1.5</Version>
        <TimerHeight>50</TimerHeight>
        <TimerWidth>225</TimerWidth>
        <TimerFormat>1.23</TimerFormat>
        <OverrideSplitColors>False</OverrideSplitColors>
        <ShowGradient>True</ShowGradient>
        <TimerColor>FFAAAAAA</TimerColor>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <CenterTimer>False</CenterTimer>
        <TimingMethod>Real Time</TimingMethod>
        <DecimalsSize>35</DecimalsSize>
      </Settings>
    </Component>
  </Components>
</Layout>